version: '3.8'


services:
    db:
      image: postgres:14-alpine
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: toor
        POSTGRES_DB: relay

    web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      ports:
        - 8000:8000